# Generated by Django 2.0.7 on 2018-08-07 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dao_dien',
            fields=[
                ('ma_tac_gia', models.AutoField(primary_key=True, serialize=False)),
                ('ten_tac_gia', models.CharField(max_length=100)),
                ('nam_sinh', models.IntegerField(default=0)),
                ('quoc_gia', models.CharField(max_length=50)),
                ('hinh', models.ImageField(null=True, upload_to='')),
                ('chieu_cao', models.CharField(max_length=10)),
                ('so_truong', models.CharField(max_length=100)),
                ('so_thich', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dien_vien',
            fields=[
                ('ma_dien_vien', models.AutoField(primary_key=True, serialize=False)),
                ('ten_dien_vien', models.CharField(max_length=100)),
                ('nam_sinh', models.IntegerField(default=0)),
                ('quoc_gia', models.CharField(max_length=50)),
                ('hinh', models.ImageField(null=True, upload_to='')),
                ('chieu_cao', models.CharField(max_length=10)),
                ('so_truong', models.CharField(max_length=100)),
                ('so_thich', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nhan_xet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(null=True)),
                ('ngay_dang', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phim',
            fields=[
                ('ma_phim', models.AutoField(primary_key=True, serialize=False)),
                ('ten_phim', models.CharField(max_length=100)),
                ('ngay_khoi_chieu', models.CharField(max_length=20)),
                ('quoc_gia', models.CharField(max_length=50)),
                ('hinh', models.ImageField(null=True, upload_to='')),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('thoi_luong', models.CharField(max_length=20)),
                ('so_tap', models.IntegerField(default=1)),
                ('luot_xem', models.IntegerField(default=0)),
                ('dao_dien', models.ManyToManyField(to='web_film.Dao_dien')),
                ('dien_vien', models.ManyToManyField(to='web_film.Dien_vien')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('id_correct_answer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tap_phim',
            fields=[
                ('ma_tap', models.AutoField(primary_key=True, serialize=False)),
                ('tap_thu', models.IntegerField(default=1)),
                ('url', models.URLField()),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_film.Phim')),
            ],
        ),
        migrations.CreateModel(
            name='The_loai',
            fields=[
                ('ma_the_loai', models.AutoField(primary_key=True, serialize=False)),
                ('ten_the_loai', models.CharField(max_length=50)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('hinh', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='phim',
            name='the_loai',
            field=models.ManyToManyField(to='web_film.The_loai'),
        ),
        migrations.AddField(
            model_name='nhan_xet',
            name='phim',
            field=models.ForeignKey(db_column='phim', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhan_xet', to='web_film.Phim'),
        ),
        migrations.AddField(
            model_name='nhan_xet',
            name='user',
            field=models.ForeignKey(db_column='nguoi_nhan_xet', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dien_vien',
            name='the_loai',
            field=models.ManyToManyField(to='web_film.The_loai'),
        ),
        migrations.AddField(
            model_name='dao_dien',
            name='the_loai',
            field=models.ManyToManyField(to='web_film.The_loai'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_film.Question'),
        ),
    ]
